apiVersion: v1
kind: Pod
metadata:
  name: import-cirros
spec:
  containers:
    - name: fc-container
      image: fedora:26
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      volumeMounts:
        - name: data
          mountPath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: cirros
