apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cirros
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
